'use client';

import React from 'react';
import { Printer, Calendar, User, Quote, AlertTriangle, CheckCircle2, ArrowLeft } from 'lucide-react';
import { Button } from '@/components/ui/Button';
import { Badge } from '@/components/ui/Badge';
import { formatDate, getSentimentLabel } from '@/lib/utils';
import Link from 'next/link';

interface ReportViewProps {
  report: {
    id: string;
    title: string;
    periodStart: string | Date;
    periodEnd: string | Date;
    contentJson: string;
    createdAt: string | Date;
    generatedBy: string;
  };
}

export function ReportView({ report }: ReportViewProps) {
  let content: any = {};
  try {
    content = JSON.parse(report.contentJson);
  } catch (err) {
    console.error('Failed to parse report JSON:', err);
  }

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="space-y-6 max-w-4xl mx-auto pb-12 print:p-0 print:m-0 print:max-w-none">
      {/* Navigation & Print Action Bar (Hidden during Print) */}
      <div className="flex items-center justify-between print:hidden">
        <Link href="/reports">
          <Button variant="outline" size="sm" className="gap-2">
            <ArrowLeft className="w-4 h-4" /> Back to Reports List
          </Button>
        </Link>
        <Button variant="primary" size="sm" onClick={handlePrint} className="gap-2">
          <Printer className="w-4 h-4" /> Print / Export PDF
        </Button>
      </div>

      {/* Main Printable Container */}
      <div className="glass-panel rounded-2xl p-8 border border-slate-800 shadow-2xl space-y-8 bg-slate-950 text-slate-100 print:border-none print:shadow-none print:bg-white print:text-black">
        {/* Report Header */}
        <div className="border-b border-slate-800/80 pb-6">
          <div className="flex items-center justify-between gap-4 mb-2">
            <h1 className="text-2xl font-black tracking-tight text-white print:text-black">{report.title}</h1>
            <span className="px-3 py-1 rounded-full text-xs font-bold bg-brand-500/10 text-brand-400 border border-brand-500/20 print:border-slate-300 print:text-slate-800">
              Voice of Customer Report
            </span>
          </div>

          <div className="flex flex-wrap items-center gap-4 text-xs text-slate-400 print:text-slate-600 mt-3">
            <div className="flex items-center gap-1.5">
              <Calendar className="w-4 h-4 text-brand-400" />
              <span>Period: {formatDate(report.periodStart)} – {formatDate(report.periodEnd)}</span>
            </div>
            <div className="flex items-center gap-1.5">
              <User className="w-4 h-4 text-indigo-400" />
              <span>Generated By: {report.generatedBy}</span>
            </div>
            <div className="flex items-center gap-1.5">
              <span className="w-2 h-2 rounded-full bg-emerald-400" />
              <span>Created on: {formatDate(report.createdAt)}</span>
            </div>
          </div>
        </div>

        {/* Executive Summary */}
        <div className="space-y-3">
          <h2 className="text-base font-bold text-white print:text-black border-l-4 border-brand-500 pl-3">
            Executive Summary
          </h2>
          <p className="text-sm text-slate-300 print:text-slate-800 leading-relaxed p-4 rounded-xl bg-slate-900/60 print:bg-slate-100 border border-slate-800/80">
            {content.executiveSummary}
          </p>
        </div>

        {/* Sentiment Overview Grid */}
        <div className="space-y-3">
          <h2 className="text-base font-bold text-white print:text-black border-l-4 border-brand-500 pl-3">
            Sentiment Breakdown
          </h2>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            <div className="p-4 rounded-xl bg-emerald-950/40 border border-emerald-500/20 text-center">
              <p className="text-xs text-emerald-400 font-semibold uppercase">Positive Feedback</p>
              <p className="text-2xl font-extrabold text-emerald-300 mt-1">{content.sentimentBreakdown?.positive || 0}</p>
            </div>
            <div className="p-4 rounded-xl bg-amber-950/40 border border-amber-500/20 text-center">
              <p className="text-xs text-amber-400 font-semibold uppercase">Neutral Feedback</p>
              <p className="text-2xl font-extrabold text-amber-300 mt-1">{content.sentimentBreakdown?.neutral || 0}</p>
            </div>
            <div className="p-4 rounded-xl bg-rose-950/40 border border-rose-500/20 text-center">
              <p className="text-xs text-rose-400 font-semibold uppercase">Negative Feedback</p>
              <p className="text-2xl font-extrabold text-rose-300 mt-1">{content.sentimentBreakdown?.negative || 0}</p>
            </div>
          </div>
        </div>

        {/* Top Customer Themes */}
        <div className="space-y-3">
          <h2 className="text-base font-bold text-white print:text-black border-l-4 border-brand-500 pl-3">
            Top Customer Themes
          </h2>
          <div className="grid grid-cols-1 gap-3">
            {content.topThemes?.map((theme: any, idx: number) => (
              <div
                key={idx}
                className="p-4 rounded-xl bg-slate-900/60 print:bg-slate-100 border border-slate-800/80 flex flex-col sm:flex-row sm:items-center justify-between gap-3"
              >
                <div>
                  <div className="flex items-center gap-2">
                    <h3 className="font-bold text-white print:text-black text-sm">{theme.name}</h3>
                    <span className="text-xs font-mono text-brand-400">({theme.count} feedback items)</span>
                  </div>
                  <p className="text-xs text-slate-400 print:text-slate-700 mt-1">{theme.summary}</p>
                </div>
                <div className="flex items-center gap-2 shrink-0">
                  <span className="text-xs font-semibold px-2.5 py-1 rounded-lg bg-slate-800 text-slate-300 border border-slate-700">
                    Sentiment: {theme.sentiment}
                  </span>
                  <span className="text-xs font-bold px-2 py-1 rounded-lg bg-brand-500/10 text-brand-300">
                    {theme.trend}
                  </span>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Key Customer Quotes */}
        <div className="space-y-3">
          <h2 className="text-base font-bold text-white print:text-black border-l-4 border-brand-500 pl-3">
            Key Customer Quotes
          </h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            {content.keyQuotes?.map((quote: any, idx: number) => (
              <div key={idx} className="p-4 rounded-xl bg-slate-900/80 print:bg-slate-100 border border-slate-800 space-y-2 text-xs">
                <div className="flex items-center justify-between">
                  <Badge variant="sentiment" value={quote.sentiment}>
                    {getSentimentLabel(quote.sentiment)}
                  </Badge>
                  <span className="text-slate-400 font-mono">{quote.channel}</span>
                </div>
                <p className="italic text-slate-200 print:text-slate-800">"{quote.quote}"</p>
                <p className="text-slate-400 font-semibold pt-1 border-t border-slate-800/60">— {quote.customer}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Emerging Issues & Spikes */}
        {content.emergingIssues && content.emergingIssues.length > 0 && (
          <div className="space-y-3">
            <h2 className="text-base font-bold text-white print:text-black border-l-4 border-rose-500 pl-3">
              Emerging Issues & Negative Spikes
            </h2>
            <div className="p-4 rounded-xl bg-rose-950/20 border border-rose-500/20 space-y-2">
              {content.emergingIssues.map((issue: string, idx: number) => (
                <div key={idx} className="flex items-center gap-2.5 text-xs text-rose-300 font-medium">
                  <AlertTriangle className="w-4 h-4 text-rose-400 shrink-0" />
                  <span>{issue}</span>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Actionable Recommendations */}
        <div className="space-y-3">
          <h2 className="text-base font-bold text-white print:text-black border-l-4 border-emerald-500 pl-3">
            Ranked Actionable Recommendations
          </h2>
          <div className="space-y-3">
            {content.recommendedActions?.map((rec: any, idx: number) => (
              <div key={idx} className="p-4 rounded-xl bg-slate-900/80 print:bg-slate-100 border border-slate-800 flex items-start gap-3">
                <div className="w-7 h-7 rounded-lg bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 flex items-center justify-center font-bold text-xs shrink-0 mt-0.5">
                  {idx + 1}
                </div>
                <div className="space-y-1">
                  <div className="flex items-center gap-2">
                    <h4 className="font-bold text-white print:text-black text-sm">{rec.title}</h4>
                    <span
                      className={`text-[10px] font-extrabold px-2 py-0.5 rounded ${
                        rec.priority === 'HIGH'
                          ? 'bg-rose-500/20 text-rose-300'
                          : rec.priority === 'MEDIUM'
                          ? 'bg-amber-500/20 text-amber-300'
                          : 'bg-slate-800 text-slate-300'
                      }`}
                    >
                      {rec.priority} PRIORITY
                    </span>
                  </div>
                  <p className="text-xs text-slate-300 print:text-slate-800 leading-relaxed">{rec.action}</p>
                  <p className="text-[11px] text-slate-500 italic">Grounded in theme: {rec.groundingTheme}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
