'use client';

import React, { useState, useEffect } from 'react';
import { GenerateReportModal } from '@/components/reports/GenerateReportModal';
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { LoadingSkeleton } from '@/components/ui/LoadingSkeleton';
import { formatDate } from '@/lib/utils';
import { FileText, Plus, Calendar, User, ArrowRight } from 'lucide-react';
import Link from 'next/link';
import { useSession } from 'next-auth/react';

export default function ReportsPage() {
  const { data: session } = useSession();
  const role = (session?.user as any)?.role || 'VIEWER';
  const canGenerate = role === 'ADMIN' || role === 'ANALYST';

  const [reports, setReports] = useState<any[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isGenerateOpen, setIsGenerateOpen] = useState(false);

  const fetchReports = async () => {
    setIsLoading(true);
    try {
      const res = await fetch('/api/reports');
      const data = await res.json();
      if (res.ok) {
        setReports(data || []);
      }
    } catch (err) {
      console.error('Failed to fetch reports:', err);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchReports();
  }, []);

  return (
    <div className="space-y-6 max-w-7xl mx-auto">
      {/* Top Banner */}
      <div className="glass-panel p-6 rounded-2xl border border-slate-800 flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h2 className="text-lg font-bold text-white flex items-center gap-2">
            <FileText className="w-5 h-5 text-brand-400" /> Voice of Customer (VoC) Reports
          </h2>
          <p className="text-xs text-slate-400 mt-1">
            Generate executive-ready reports with sentiment shifts, key quotes, emerging spikes, and prioritized actions.
          </p>
        </div>

        {canGenerate && (
          <Button variant="primary" onClick={() => setIsGenerateOpen(true)} className="gap-2 shrink-0">
            <Plus className="w-4 h-4" /> Generate VoC Report
          </Button>
        )}
      </div>

      {/* Reports List */}
      <div>
        <h3 className="text-sm font-bold text-white mb-3">Generated Reports History</h3>

        {isLoading ? (
          <LoadingSkeleton count={3} height="h-24" />
        ) : reports.length === 0 ? (
          <div className="p-12 text-center glass-panel rounded-2xl border border-slate-800">
            <FileText className="w-10 h-10 text-slate-500 mx-auto mb-3" />
            <p className="text-sm font-semibold text-slate-300">No reports generated yet.</p>
            <p className="text-xs text-slate-500 mt-1">Click "Generate VoC Report" to create your first report.</p>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {reports.map((report) => (
              <Link key={report.id} href={`/reports/${report.id}`}>
                <Card className="hover:border-brand-500/50 hover:bg-slate-800/40 transition-all cursor-pointer group p-5">
                  <div className="flex items-start justify-between gap-2 mb-3">
                    <h4 className="text-base font-bold text-white group-hover:text-brand-300 transition-colors">
                      {report.title}
                    </h4>
                    <span className="text-[10px] uppercase font-bold px-2 py-0.5 rounded bg-brand-500/10 text-brand-400 border border-brand-500/20 shrink-0">
                      VoC Report
                    </span>
                  </div>

                  <div className="space-y-1.5 text-xs text-slate-400 pt-2 border-t border-slate-800/60">
                    <div className="flex items-center justify-between">
                      <span className="flex items-center gap-1.5">
                        <Calendar className="w-3.5 h-3.5 text-brand-400" />
                        <span>Period: {formatDate(report.periodStart)} – {formatDate(report.periodEnd)}</span>
                      </span>
                    </div>

                    <div className="flex items-center justify-between pt-1">
                      <span className="flex items-center gap-1.5">
                        <User className="w-3.5 h-3.5 text-indigo-400" />
                        <span>Generated by {report.generatedBy}</span>
                      </span>
                      <span className="text-brand-400 font-semibold group-hover:translate-x-0.5 transition-transform inline-flex items-center gap-1">
                        View Report <ArrowRight className="w-3.5 h-3.5" />
                      </span>
                    </div>
                  </div>
                </Card>
              </Link>
            ))}
          </div>
        )}
      </div>

      {/* Modal */}
      <GenerateReportModal
        isOpen={isGenerateOpen}
        onClose={() => setIsGenerateOpen(false)}
        onSuccess={fetchReports}
      />
    </div>
  );
}
